<?php
$quotes = [
    ["Give me six hours to chop down a tree and I will spend the first four sharpening the axe.","Abraham Lincoln"],
    ["We have to continually be jumping off cliffs and developing our wings on the way down.","Kurt Vonnegut"],
    ["We are what we repeatedly do. Excellence, then, is not an act, but a habit.","Aristotle"],
    ["Those who don't believe in magic will never find it.","Roald Dahl"],
    ["You see things; and you say Why? But I dream things that never were; and I say Why not?","George Bernard Shaw"],
    ["Opportunity is missed by most people because it is dressed in overalls and looks like work.","Thomas Edison"],
    ["If you're going through hell, keep going.","Winston Churchill"],
    ["If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much.","Jim Rohn"],
    ["Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.","Thomas Edison"],
    ["Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice.","Wayne Dyer"],
    ["I don't believe you have to be better than everybody else. I believe you have to be better than you ever thought you could be.","Ken Venturi"],
    ["Learn from the past, set vivid, detailed goals for the future, and live in the only moment of time over which you have any control: now.","Denis Waitley"],
    ["Even if you fall on your face, you're still moving forward.","Victor Kiam"],
    ["We are taught you must blame your father, your sisters, your brothers, the school, the teachers - but never blame yourself. It's never your fault. But it's always your fault, because if you wanted to change you're the one who has got to change.","Katharine Hepburn"],
    ["If you want to succeed you should strike out on new paths, rather than travel the worn paths of accepted success.","John D. Rockefeller"],
    ["Things do not happen. Things are made to happen.","John F. Kennedy"],
    ["You have to learn the rules of the game. And then you have to play better than anyone else.","Albert Einstein"],
    ["I'd rather attempt to do something great and fail than to attempt to do nothing and succeed.","Robert H. Schuller"],
    ["The harder the conflict, the more glorious the triumph.","Thomas Paine"],
    ["You can't build a reputation on what you are going to do.","Henry Ford"],
    ["The secret of getting ahead is getting started.","Mark Twain"],
    ["Do your work with your whole heart, and you will succeed - there's so little competition.","Elbert Hubbard"],
    ["Small deeds done are better than great deeds planned.","Peter Marshall"],
    ["The wise does at once what the fool does at last.","Baltasar Gracian"],
    ["I've found that luck is quite predictable. If you want more luck, take more chances. Be more active. Show up more often.","Brian Tracy"],
    ["If you do not hope, you will not find what is beyond your hopes.","St. Clement of Alexandra"],
    ["Dream big and dare to fail.","Norman Vaughan"],
    ["With will one can do anything.","Samuel Smiles"],
    ["We are all inventors, each sailing out on a voyage of discovery, guided each by a private chart, of which there is no duplicate. The world is all gates, all opportunities.","Ralph Waldo Emerson"],
    ["Seek the lofty by reading, hearing and seeing great work at some moment every day.","Thornton Wilder"],
    ["The only way of finding the limits of the possible is by going beyond them into the impossible.","Arthur C. Clarke"],
    ["Without inspiration the best powers of the mind remain dormant. There is a fuel in us which needs to be ignited with sparks.","Johann Gottfried Von Herder"],
    ["If the wind will not serve, take to the oars.","Latin Proverb"],
    ["Men's best successes come after their disappointments.","Henry Ward Beecher"],
    ["You cannot plough a field by turning it over in your mind.","Unknown"],
    ["The best way out is always through.","Robert Frost"],
    ["Do not wait to strike till the iron is hot; but make it hot by striking.","William B. Sprague"],
    ["Nothing will ever be attempted if all possible objections must first be overcome.","Samuel Johnson"],
    ["Fortune favors the brave.","Publius Terence"],
    ["When the best things are not possible, the best may be made of those that are.","Richard Hooker"],
    ["He who hesitates is lost.","Proverb"],
    ["If you want to succeed in the world you must make your own opportunities as you go on. The man who waits for some seventh wave to toss him on dry land will find that the seventh wave is a long time a coming. You can commit no greater folly than to sit by the roadside until someone comes along and invites you to ride with him to wealth or influence.","John B. Gough"],
    ["An oak is not felled at one blow.","Spanish Proverb"],
    ["In doubtful matters boldness is everything.","Publilius Syrus"],
    ["Great spirits have always encountered violent opposition from mediocre minds.","Albert Einstein"],
    ["Believe with all of your heart that you will do what you were made to do.","Orison Swett Marden"],
    ["Knowing is not enough; we must apply. Willing is not enough; we must do.","Johann Wolfgang von Goethe"],
    ["We are still masters of our fate. We are still captains of our souls.","Winston Churchill"],
    ["Nothing great was ever achieved without enthusiasm.","Ralph Waldo Emerson"],
    ["For hope is but the dream of those that wake.","Matthew Prior"],
    ["Constant dripping hollows out a stone.","Lucretius"],
    ["Nothing contributes so much to tranquilise the mind as a steady purpose - a point on which the soul may fix its intellectual eye.","Mary Shelley"],
    ["Try not to become a man of success but a man of value.","Albert Einstein"],
    ["If you have built castles in the air, your work need not be lost; that is where they should be. Now put foundations under them.","Henry David Thoreau"],
    ["Inspiration and genius – one and the same.","Victor Hugo"],
    ["To find what you seek in the road of life, the best proverb of all is that which says: 'Leave no stone unturned.'","Edward Bulwer Lytton"],
    ["Doubt whom you will, but never yourself.","Christian Nestell Bovee"],
    ["If you would create something, you must be something.","Johann Wolfgang von Goethe"],
    ["Every artist was first an amateur.","Ralph Waldo Emerson"],
    ["The more difficulties one has to encounter, within and without, the more significant and the higher in inspiration his life will be.","Horace Bushnell"],
    ["I avoid looking forward or backward, and try to keep looking upward.","Charlotte Bront&euml;"],
    ["Life has no smooth road for any of us; and in the bracing atmosphere of a high aim the very roughness stimulates the climber to steadier steps, till the legend, over steep ways to the stars, fulfills itself.","W. C. Doane"],
    ["Experience is the child of thought, and thought is the child of action.","Benjamin Disraeli"],
    ["Don't wait for extraordinary opportunities. Seize common occasions and make them great.","Orison Swett Marden"],
    ["Do we not all agree to call rapid thought and noble impulse by the name of inspiration?","George Eliot"],
    ["No great man ever complains of want of opportunities.","Ralph Waldo Emerson"],
    ["Men do less than they ought, unless they do all they can.","Thomas Carlyle"],
    ["Happy are those who dream dreams and are ready to pay the price to make them come true.","Leon J. Suenes"],
    ["The power of imagination makes us infinite.","John Muir"],
    ["First say to yourself what you would be; and then do what you have to do.","Epictetus"],
    ["You miss 100% of the shots you don't take.","Wayne Gretzky"],
    ["Along with success comes a reputation for wisdom.","Euripides"],
    ["They can because they think they can.","Virgil"],
    ["Nothing can stop the man with the right mental attitude from achieving his goal; nothing on earth can help the man with the wrong mental attitude. ","Thomas Jefferson"],
    ["Keep steadily before you the fact that all true success depends at last upon yourself.","Theodore T. Hunger"],
    ["We are all motivated by a keen desire for praise, and the better a man is, the more he is inspired to glory.","Cicero"],
    ["The thing always happens that you really believe in; and the belief in a thing makes it happen.","Frank Loyd Wright"],
    ["The surest way not to fail is to determine to succeed.","Richard Brinsley Sheridan"],
    ["A failure is a man who has blundered, but is not able to cash in on the experience.","Elbert Hubbard"],
    ["There is only one success--to be able to spend your life in your own way.","Christopher Morley"],
    ["Success is the child of audacity.","Benjamin Disraeli"],
    ["Failures to heroic minds are the stepping stones to success.","Thomas Chandler Haliburton"],
    ["The secret of success is to know something nobody else knows.","Aristotle Onassis"],
    ["The greatest results in life are usually attained by simple means and the exercise of ordinary qualities. These may for the most part be summed in these two: common-sense and perseverance.","Owen Feltham"],
    ["The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.","Vince Lombardi"],
    ["Everyone has a fair turn to be as great as he pleases.","Jeremy Collier"],
    ["I cannot give you the formula for success, but I can give you the formula for failure--which is: Try to please everybody. ","Herbert Bayard Swope"],
    ["Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome while trying to succeed.","Booker T. Washington"],
    ["Success does not consist in never making blunders, but in never making the same one a second time.","Josh Billings"],
    ["Success is the good fortune that comes from aspiration, desperation, perspiration and inspiration.","Evan Esar"],
    ["He is great enough who is his own master.","Bishop Hail"],
    ["If you wish success in life, make perseverance your bosom friend, experience your wise counselor, caution your elder brother, and hope your guardian genius.","Jospeph Addison"],
    ["Impatience never commanded success.","Edwin H. Chapin"],
    ["Careful thinking and hard work will solve nearly all your problems. Try and see for yourself.","Ullery"],
    ["The talent of success is nothing more than doing what you can do, well.","Henry W. Longfellow"],
    ["The man who makes a success of an important venture never wails for the crowd. He strikes out for himself. It takes nerve, it takes a great lot of grit; but the man that succeeds has both. Anyone can fail. The public admires the man who has enough confidence in himself to take a chance. These chances are the main things after all. The man who tries to succeed must expect to be criticized. Nothing important was ever done but the greater number consulted previously doubted the possibility. Success is the accomplishment of that which most people think can't be done.","C. V. White"],
    ["If at first you don't succeed, try, try again. Then quit. There's no use being a damn fool about it.","W.C. Fields"],
    ["Success is the sum of small efforts, repeated day in and day out.","Robert Collier"],
    ["When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.","Helen Keller"],
    ["Happiness resides not in possessions and not in gold; the feeling of happiness dwells in the soul.","Democritus"],
    ["The happiness of your life depends upon the quality of your thoughts; therefore guard accordingly.","Marcus Aurelius"],
    ["People with many interests live, not only longest, but happiest.","George Matthew Allen"],
    ["In the hopes of reaching the moon men fail to see the flowers that blossom at their feet.","Albert Schweitzer"],
    ["Happiness is not achieved by the conscious pursuit of happiness; it is generally the by-product of other activities.","Aldous Huxley"],
    ["There is only one person who could ever make you happy, and that person is you.","David Burns"],
    ["The happiness of life is made up of minute fractions – the little soon-forgotten charities of a kiss, a smile, a kind look, a heartfelt compliment in the disguise of a playful raillery, and the countless other infinitesimal of pleasurable thought and genial feeling.","Samuel Taylor Coleridge"],
    ["The man is happiest who lives from day to day and asks no more, garnering the simple goodness of life.","Euripides"],
    ["There is no happiness except in the realization that we have accomplished something.","Henry Ford"],
    ["Happiness consists in activity: such is the constitution of our nature; it is a running stream, and not a stagnant pool.","John M. Good"],
    ["Happiness is not a state to arrive at, but a manner of traveling.","Margaret Lee Runbeck"],
    ["A light heart lives long.","William Shakespeare"],
    ["We deem those happy who, from the experience of life, have learned to bear its ills, without being overcome by them.","Juvenal"],
    ["Men spend their lives in anticipations, in determining to be vastly happy at some period when they have time. But the present time has one advantage over every other – it is our own. Past opportunities are gone, future have not come. We may lay in a stock of pleasures, as we would lay in a stock of wine; but if we defer the tasting of them too long, we shall find that both are soured by age.","Charles Caleb Colton"],
    ["Who is the happiest of men? He who values the merits of others, and in their pleasure takes joy, even as though 'twere his own. ","Johann Wolfgang von Goethe"],
    ["The chances are that you have already come to believe that happiness is unattainable. But men have attained it. And they have attained it by realising that happiness does not spring from the procuring of physical or mental pleasure, but from the development of reason and the adjustment of conduct to principles.","Arnold Bennett"],
    ["Happiness is not a matter of events, it depends upon the tides of the mind.","Alice Meynell"],
    ["Fortify yourself with contentment, for this is an impregnable fortress.","Epictetus"],
    ["Happiness depends more on the inward disposition of mind than on outward circumstances.","Benjamin Franklin"],
    ["There is only one way to happiness, and that is to cease worrying about things which are beyond the power of our will.","Epictetus"],
    ["You're happiest while you're making the greatest contribution.","Robert F. Kennedy"],
    ["Action may not always bring happiness; but there is no happiness without action.","Benjamin Disraeli"],
    ["Great effort from great motives is the best definition of a happy life.","William Ellery Channing"],
    ["The greater part of our happiness depends on our dispositions, and not on our circumstances.","Martha Washington"],
    ["There is more to life than increasing its speed.","Mahatma Gandhi"],
    ["Happiness grows at our own firesides, and is not to be picked in strangers' gardens.","Douglas Jerrold"],
    ["Happiness is where we find it, but rarely where we seek it.","J. Petit Senn"],
    ["To be happy, we must not be too concerned with others.","Albert Camus"],
    ["The only way on earth to multiply happiness is to divide it.","Paul Scherer"],
    ["Happiness depends upon ourselves.","Aristotle"],
    ["Try to be happy in this present moment, and put not off being so to a time to come, as though that time should be of another make from this which has already come and is ours.","Thomas Fuller"],
    ["Knowledge of what is possible is the beginning of happiness.","George Santayana"],
    ["No man is happy who does not think himself so.","Publilius Syrus"],
    ["Our minds are as different as our faces: we are all traveling to one destination; happiness; but few are going by the same road.","Charles Caleb Colton"],
    ["The imagination exercises a powerful influence over every act of sense, thought, reason, -- over every idea.","Latin Proverb"],
    ["Solitude is as needful to the imagination as society is wholesome for the character.","James Russel Lowell"],
    ["Far away in the sunshine are my highest aspirations. I may not reach them, but I can look up and see their beauty, believe in them, and try to follow where they lead.","Louisa May Alcott"],
    ["Imagination is more important than knowledge.","Albert Einstein"],
    ["Imagination rules the world.","Napoleon"],
    ["He who has imagination without learning, has wings and no feet.","Joseph Joubert"],
    ["A strong imagination begetteth opportunity.","Michel de Montaigne"],
    ["Your imagination is your preview of life's coming attractions.","Albert Einstein"],
    ["Where beams of imagination play, The memory's soft figures melt away.","Alexander Pope"],
    ["Believe that you have it, and you have it.","Latin Proverb"],
    ["The real voyage of discovery consists not in seeking new landscapes but in having new eyes.","Marcel Proust"],
    ["The imagination is the secret and marrow of civilization. ","Henry Ward Beecher"],
    ["Imagination is the eye of the soul.","Joseph Joubert"],
    ["You cannot depend on your eyes when your imagination is out of focus.","Mark Twain"],
    ["I have spread my dreams beneath your feet. Tread softly because you tread on my dreams.","W.B. Yeats"],
    ["Go confidently in the direction of your dreams. Live the life you have imagined.","Henry David Thoreau"],
    ["Every great dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.","Harriet Tubman"],
    ["Reach high, for stars lie hidden in your soul. Dream deep, for every dream precedes the goal.","Pamela Vaull Starr"],
    ["All men dream but not equally. Those who dream by night in the dusty recesses of their minds wake in the day to find that it was vanity; but the dreamers of the day are dangerous men, for they may act their dream with open eyes to make it possible.","T.E. Lawrence"],
    ["Our truest life is when we are in dreams awake.","Henry David Thoreau"],
    ["So often times it happens that we live our lives in chains and we never even know we have the key.","The Eagles"],
    ["The end of wisdom is to dream high enough not to lose the dream in the seeking of it.","William Faulkner"],
    ["I like the dreams of the future better than the history of the past.","Patrick Henry"],
    ["Hold fast to dreams, for if dreams die, life is a broken winged bird that cannot fly.","Lanston Hughes"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["Commitment leads to action. Action brings your dream closer. ","Marcia Wieder"],
    ["Dreams are the touchstones of our character.","Henry David Thoreau"],
    ["The question for each man to settle is not what he would do if he had means, time, influence and educational advantages; the question is what he will do with the things he has. The moment a young man ceases to dream or to bemoan his lack of opportunities and resolutely looks his conditions in the face, and resolves to change them, he lays the corner-stone of a solid and honorable success.","Hamilton Wright Mabie"],
    ["The best way to make your dreams come true is to wake up.","Paul Valery"],
    ["A skillful man reads his dreams for self-knowledge, yet not the details but the quality.","Ralph Waldo Emerson"],
    ["Our waking hours form the text of our lives, our dreams, the commentary.","Anonymous"],
    ["Hope is the dream of the waking man.","French Proverb"],
    ["To unpathed waters, undreamed shores.","William Shakespeare"],
    ["You cannot dream yourself into a character; you must hammer and forge yourself one.","Henry David Thoreau"],
    ["Be your character what it will, it will be known, and nobody will take it upon your word.","Lord Chesterfield"],
    ["Reputation is for time; character is for eternity.","J. B. Gough"],
    ["Nothing of character is really permanent but virtue and personal worth.","Daniel Webster"],
    ["Character is like a tree and reputation is like its shadow. The shadow is what we think of it; the tree is the real thing.","Abraham Lincoln"],
    ["The essential thing is not knowledge, but character.","Joseph Le Conte"],
    ["The great hope of society is individual character.","William Ellery Channing"],
    ["A good name will shine forever. ","Proverb"],
    ["A fair reputation is a plant, delicate in its nature, and by no means rapid in its growth. It will not shoot up in a night like the gourd of the prophet; but, like that gourd, it may perish in a night.","Jeremy Taylor"],
    ["Talents are best nurtured in solitude. Character is best formed in the stormy billows of the world.","Johann Wolfgang Von Goethe"],
    ["Our character is but the stamp on our souls of the free choices of good and evil we have made through life.","John C. Geikie"],
    ["Character is a diamond that scratches every other stone.","Cyrus A. Bartol"],
    ["It matters not what you are thought to be, but what you are.","Publilius Syrus"],
    ["In the stormy current of life characters are weights or floats which at one time make us glide along the bottom, and at another maintain us on the surface.","Hippolyte Taine"],
    ["Character is what you think in the dark.","Dwight L. Moody"],
    ["Character is the real foundation of all worthwhile success.","John Hays Hammond"],
    ["Nature magically suits a man to his fortunes, by making them the fruit of his character.","Ralph Waldo Emerson"],
    ["Characters do not change. Opinions alter, but characters are only developed.","Benjamin Disraeli"],
    ["A man's character is like his shadow, which sometimes follows and sometimes precedes him, and which is occasionally longer, occasionally shorter, than he is.","Madame de la Rochejuquelein"],
    ["Do what you know and perception is converted into character.","Ralph Waldo Emerson"],
    ["Men best show their character in trifles, where they are not on their guard. It is in the simplest habits, that we often see the boundless egotism which pays no regard to the feelings of others and denies nothing to itself.","Arthur Schopenhauer"],
    ["Every man, as to character, is the creature of the age in which he lives. Very few are able to raise themselves above the ideas of their times.","Voltaire"],
    ["It is of little traits that the greatest human character is composed.","William Winter"],
    ["Character is perfectly educated will.","Novalis"],
    ["Character and personal force are the only investments that are worth anything.","Walt Whitman"],
    ["Every thought willingly contemplated, every word meaningly spoken, every action freely done, consolidates itself in the character, and will project itself onward in a permanent continuity.","Henry Giles"],
    ["Character is, for the most part, simply habit become fixed.","C. H. Parkhurst"],
    ["We are builders of our own characters. We have different positions, spheres, capacities, privileges, different work to do in the world, different temporal fabrics to raise; but we are all alike in this, – all are architects of fate.","John Fothergill Waterhouse Ware"],
    ["Character is, in the long run, the decisive factor in the life of individuals and of nations alike.","Theodore Roosevelt"],
    ["Actions, looks, words and steps form the alphabet by which you may spell character. ","Johann Kasper Lavater"],
    ["Every human being is intended to have a character of his own; to be what no others are, and to do what no other can do.","William Henry Channing"],
    ["Let us not say, Every man is the architect of his own fortune; but let us say, Every man is the architect of his own character.","George Dana Boardman"],
    ["Fate is character.","William Winter"],
    ["Character is higher than intellect. A great soul will be strong to live, as well as strong to think.","Ralph Waldo Emerson"],
    ["Do not follow where the path may lead. Go instead where there is no path and leave a trail.","Harold R. McAlindon"],
    ["Leadership: The art of getting someone else to do something you want done because he wants to do it.","Dwight D. Eisenhower"],
    ["There go the people. I must follow them for I am their leader.","Alexandre Ledru-Rollin"],
    ["What chance gathers she easily scatters. A great person attracts great people and knows how to hold them together.","Johann Wolfgang Von Goethe"],
    ["A general is just as good or just as bad as the troops under his command make him.","General Douglas MacArthur"],
    ["Men are governed only by serving them; the rule is without exception.","V. Cousin"],
    ["The real leader has no need to lead - he is content to point the way.","Henry Miller"],
    ["Not the cry, but the flight of a wild duck, leads the flock to fly and follow.","Chinese Proverb"],
    ["Be known for pleasing others, espcecially if you govern them...Ruling others has one advantage: you can do more good than anyone else.","Baltasar Graci&aacute;n"],
    ["Go to the people. Learn from them. Live with them. Start with what they know. Build with what they have. The best of leaders when the job is done, when the task is accomplished, the people will say we have done it ourselves.","Lao Tzu"],
    ["A leader is a dealer in hope.","Napoleon Bonaparte"],
    ["Rely on your own strength of body and soul. Take for your star self-reliance, faith, honesty and industry. Don't take too much advice – keep at the helm and steer your own ship, and remember that the great art of commanding is to take a fair share of the work. Fire above the mark you intend to hit. Energy, invincible determination with the right motive, are the levers that move the world.","Noah Porter"],
    ["There is always room for a man of force and he makes room for many. Society is a troop of thinkers and the best heads among them take the best places.","Ralph Waldo Emerson"],
    ["If your actions inspire others to dream more, learn more, do more and become more, you are a leader.","John Quincy Adams"],
    ["The people follow the example of those above them.","Chinese Proverb"],
    ["He who has never learned to obey cannot be a good commander.","Aristotle"],
    ["The ultimate measure of a man is not where he stands in moments of comfort, but where he stands at times of challenge and controversy.","Martin Luther King, Jr."],
    ["Any one can hold the helm when the sea is calm.","Publilius Syrus"],
    ["Never tell people how to do things. Tell them what to do and they will surprise you with their ingenuity.","George Patton"],
    ["Where there is no vision, the people perish.","Proverbs 29:18"],
    ["Misfortunes, untoward events, lay open, disclose the skill of a general, while success conceals his weakness, his weak points.","Horace"],
    ["In this world a man must either be an anvil or hammer.","Henry W. Longfellow"],
    ["Leadership does not always wear the harness of compromise.","Woodrow Wilson"],
    ["The greater a man is in power above others, the more he ought to excel them in virtue. None ought to govern who is not better than the governed.","Publilius Syrus"],
    ["Take time to deliberate; but when the time for action arrives, stop thinking and go in.","Andrew Jackson"],
    ["A bold onset is half the battle.","Giuseppe Garibaldi"],
    ["The power is detested, and miserable the life, of him who wishes to be feared rather than to be loved.","Cornelius Nepos"],
    ["To be a great leader and so always master of the situation, one must of necessity have been a great thinker in action. An eagle was never yet hatched from a goose's egg.","James Thomas"],
    ["Ill can he rule the great that cannot reach the small.","Edmund Spenser"],
    ["He who has learned how to obey will know how to command.","Solon"],
    ["When I give a minister an order, I leave it to him to find the means to carry it out.","Napoleon Bonaparte"],
    ["No man can stand on top because he is put there.","H. H. Vreeland"],
    ["A ruler should be slow to punish and swift to reward.","Ovid"],
    ["It is impossible to imagine anything which better becomes a ruler than mercy.","Seneca"],
    ["No man is good enough to govern another man without that other's consent.","Abraham Lincoln"],
    ["What you cannot enforce / Do not command.","Sophocles"],
    ["No general can fight his battles alone. He must depend upon his lieutenants, and his success depends upon his ability to select the right man for the right place.","Philip Armour"],
    ["To do great things is difficult; but to command great things is more difficult.","Friedrich Nietzsche"],
    ["It is absurd that a man should rule others, who cannot rule himself.","Latin Proverb"],
    ["Let him who would be moved to convince others, be first moved to convince himself.","Thomas Carlyle"],
    ["A good general not only sees the way to victory; he also knows when victory is impossible.","Polybius"],
    ["A goal is a dream with a deadline.","Napoleon Hill"],
    ["In everything the ends well defined are the secret of durable success.","Victor Cousins"],
    ["Arriving at one goal is the starting point to another.","John Dewey"],
    ["Failures do what is tension relieving, while winners do what is goal achieving.","Dennis Waitley"],
    ["A man should have any number of little aims about which he should be conscious and for which he should have names, but he should have neither name for, nor consciousness concerning, the main aim of his life.","Samuel Butler"],
    ["Goals are the fuel in the furnace of achievement.","Brian Tracy"],
    ["The great and glorious masterpiece of man is to know how to live to purpose.","Michel de Montaigne"],
    ["Ah, but a man's reach should exceed his grasp, or what's a heaven for?","Robert Browning"],
    ["Purpose is what gives life a meaning.","C. H. Parkhurst"],
    ["The significance of a man is not in what he attains but in what he longs to attain.","Kahlil Gibran"],
    ["Every ceiling, when reached, becomes a floor, upon which one walks as a matter of course and prescriptive right.","Aldous Huxley"],
    ["If you don't know where you are going, you'll end up someplace else.","Yogi Berra"],
    ["He who would arrive at the appointed end must follow a single road and not wander through many ways.","Seneca"],
    ["Some men give up their designs when they have almost reached the goal; while others, on the contrary, obtain a victory by exerting, at the last moment, more vigorous efforts than before.","Polybius"],
    ["In all things that you do, consider the end.","Solon"],
    ["Life can be pulled by goals just as surely as it can be pushed by drives.","Viktor Frankl"],
    ["Aim at the sun, and you may not reach it; but your arrow will fly far higher than if aimed at an object on a level with yourself.","J. Howes"],
    ["The virtue lies in the struggle, not in the prize.","Richard Monckton Milnes"],
    ["To reach a port, we must sail – Sail, not tie at anchor – Sail, not drift.","Franklin Roosevelt"],
    ["Our plans miscarry because they have no aim. When a man does not know what harbor he is making for, no wind is the right wind.","Seneca"],
    ["However brilliant an action may be, it should not be accounted great when it is not the result of a great purpose.","Francois de la Rochefoucauld"],
    ["It is not enough to take steps which may some day lead to a goal; each step must be itself a goal and a step likewise.","Johann Wolfgang von Goethe"],
    ["A good archer is known not by his arrows but by his aim.","Thomas Fuller"],
    ["Who aims at excellence will be above mediocrity; who aims at mediocrity will be far short of it.","Burmese Saying"],
    ["In absence of clearly defined goals, we become strangely loyal to performing daily acts of trivia.","Unknown"],
    ["Don't bunt. Aim out of the ballpark.","David Ogilvy"],
    ["There are two things to aim at in life; first to get what you want, and after that to enjoy it. Only the wisest of mankind has achieved the second.","Logan Pearsall Smith"],
    ["It is easier to be wise for others than for ourselves.","Francois De La Rochefoucauld"],
    ["The art of being wise is knowing what to overlook.","William James"],
    ["The first step in the acquisition of wisdom is silence, the second listening, the third memory, the fourth practice, the fifth teaching others.","Solomon Ibn Gabriol"],
    ["Wisdom is better than gold or silver.","German Proverb"],
    ["Years teach us more than books.","Berthold Auerbach"],
    ["It is best to learn wisdom by the experience of others.","Latin Proverb"],
    ["The wisdom of nations lies in their proverbs, which are brief and pithy.","William Penn"],
    ["The middle course is the best.","Cleobulus"],
    ["The wise man should be prepared for everything that does not lie within his control.","Pythagoras"],
    ["The only medicine for suffering, crime, and all the other woes of mankind, is wisdom.","Thomas Huxley"],
    ["A wise man learns by the mistakes of others, a fool by his own.","Latin Proverb"],
    ["Silence does not always mark wisdom.","Samuel Taylor Coleridge."],
    ["Measure a thousand times and cut once.","Turkish Proverb"],
    ["No man was ever wise by chance.","Seneca"],
    ["He has not learned the lesson of life who does not every day surmount a fear.","Ralph Waldo Emerson"],
    ["Not to know at large of things remote From use, obscure and subtle, but to know That which before us lies in daily life, Is the prime wisdom.","John Milton"],
    ["By associating with wise people you will become wise yourself.","Menander"],
    ["The seat of knowledge is in the head, of wisdom, in the heart.","William Hazlitt"],
    ["Of all parts of wisdom the practice is the best.","John Tillotson"],
    ["The larger the island of knowledge, the longer the shore line of wonder.","Ralph W. Sockman"],
    ["The more a man knows, the more he forgives.","Catherine the Great"],
    ["A loving heart is the truest wisdom.","Charles Dickens"],
    ["One who understands much displays a greater simplicity of character than one who understands little.","Alexander Chase"],
    ["How prone to doubt, how cautious are the wise!","Homer"],
    ["The man of wisdom is never of two minds; the man of benevolence never worries; the man of courage is never afraid.","Confucius"],
    ["Wisdom is the sunlight of the soul.","German Proverb"],
    ["The way to gain a good reputation, is to endeavor to be what you desire to appear.","Socrates"],
    ["The fact is, that to do anything in the world worth doing, we must not stand back shivering and thinking of the cold and danger, but jump in and scramble through as well as we can.","Robert Cushing"],
    ["We only become what we are by the radical and deep-seated refusal of that which others have made of us.","Jean-Paul Sartre"],
    ["The searching-out and thorough investigation of truth ought to be the primary study of man.","Cicero"],
    ["The only journey is the journey within.","Rainer Maria Rilke"],
    ["It is not easy to find happiness in ourselves, and it is not possible to find it elsewhere.","Agnes Repplier"],
    ["Know thyself means this, that you get acquainted with what you know, and what you can do.","Menander"],
    ["Yes, know thyself: in great concerns or small, Be this thy care, for this, my friend, is all.","Juvenal"],
    ["Men soon the faults of others learn A few their virtues, too, find out; But is there one – I have a doubt – Who can his own defects discern?","Sanskrit Proverb"],
    ["Collect as precious pearls the words of the wise and virtuous.","Abd-el-Kadar"],
    ["If we do not plant knowledge when young, it will give us no shade when we are old.","Lord Chesterfield"],
    ["Our business in life is not to get ahead of other people, but to get ahead of ourselves.","Maltbie D. Matlock"],
    ["If you have an hour, will you not improve that hour, instead of idling it away?","Lord Chesterfield"],
    ["Follow your honest convictions, and stay strong.","William Thackeray"],
    ["As the sculptor devotes himself to wood and stone, I would devote myself to my soul.","Toyohiko Kagawa"],
    ["The most difficult thing in life is to know yourself.","Thales"],
    ["He that will not reflect is a ruined man.","Asian Proverb"],
    ["Every day do something that will inch you closer to a better tomorrow.","Doug Firebaugh"],
    ["Be not afraid of growing slowly; be afraid only of standing still.","Chinese Proverb"],
    ["God ever works with those who work with will.","Aeschylus"],
    ["Insist on yourself. Never imitate.","Ralph Waldo Emerson"],
    ["Heaven never helps the man who will not act.","Sophocles"],
    ["Knowing yourself is the beginning of all wisdom.","Aristotle"],
    ["Our ideas, like orange-plants, spread out in proportion to the size of the box which imprisons the roots.","Edward Bulwer Lytton"],
    ["We are sometimes as different from ourselves as we are from others.","Francois de La Rochefoucauld"],
    ["In learning to know other things, and other minds, we become more intimately acquainted with ourselves, and are to ourselves better worth knowing.","Philip Gilbert Hamilton"],
    ["It is only the very wisest and the very stupidest who cannot change.","Confucius"],
    ["We are either progressing or retrograding all the while; there is no such thing as remaining stationary in this life.","James Freeman Clarke"],
    ["To conquer oneself is the best and noblest victory; to be vanquished by one's own nature is the worst and most ignoble defeat.","Plato"],
    ["Everybody wants to be somebody; nobody wants to grow.","Johann Wolfgang von Goethe"],
    ["The happiest life is that which constantly exercises and educates what is best in us.","Hamerton"],
    ["Change and growth take place when a person has risked himself and dares to become involved with experimenting with his own life.","Herbert Otto"],
    ["Heed the still small voice that so seldom leads us wrong, and never into folly.","Marquise du Deffand"],
    ["Your real influence is measured by your treatment of yourself.","A. Bronson Alcott"],
    ["If we all did the things we are capable of, we would astound ourselves.","Thomas Edison"],
    ["A man who finds no satisfaction in himself will seek for it in vain elsewhere.","La Rochefoucauld"],
    ["Fear less, hope more, eat less, chew more, whine less, breathe more, talk less, say more, hate less, love more, and good things will be yours.","Swedish Proverb"],
    ["Make it thy business to know thyself, which is the most difficult lesson in the world.","Miguel de Cervantes"],
    ["The best rules to form a young man are: to talk little, to hear much, to reflect alone upon what has passed in company, to distrust one's own opinions, and value others that deserve it.","Sir William Temple"],
    ["Exert your talents, and distinguish yourself, and don't think of retiring from the world, until the world will be sorry that you retire.","Samuel Johnson"],
    ["You must look into other people as well as at them.","Lord Chesterfield"],
    ["A man's own good breeding is the best security against other people's ill manners.","Lord Chesterfield"],
    ["The secret of many a man's success in the world resides in his insight into the moods of men and his tact in dealing with them.","J. G. Holland"],
    ["To rejoice in another's prosperity, is to give content to your own lot: to mitigate another's grief, is to alleviate or dispel your own.","Thomas Edwards"],
    ["Hear the meaning within the word.","William Shakespeare"],
    ["Charity, good behaviour, amiable speech, unselfishness – these by the chief sage have been declared the elements of popularity.","Burmese Proverb"],
    ["Kind words are the music of the world.","F. W. Faber"],
    ["We are far more liable to catch the vices than the virtues of our associates.","Denis Diderot"],
    ["Arguing with a fool proves there are two.","Doris M. Smith"],
    ["Be courteous to all, but intimate with few; and let those be well-tried before you give them your confidence.","George Washington"],
    ["Look to be treated by others as you have treated others.","Publilius Syrus"],
    ["I have made it a rule never to be with a person ten minutes without trying to make him happier.","Anonymous"],
    ["Success in life, in anything, depends upon the number of person's that one can make himself agreeable to.","Thomas Carlyle"],
    ["Never part without loving words to think of during your absence. It may be that you will not meet again in this life.","Jean Paul Richter"],
    ["Let us believe neither half of the good people tell us of ourselves, nor half of the evil they say of others.","J. Petit Senn"],
    ["The more you say, the less people remember.","Fran&ccedil;ois F&eacute;nelon"],
    ["Never lose a chance of saying a kind word.","William Thackeray"],
    ["The soul of conversation is sympathy.","Thomas Campbell"],
    ["It is always good to know, if only in passing, charming human beings. It refreshes one like flowers and woods and clear brooks.","George Eliot"],
    ["Every man is a volume if you know how to read him.","William Ellery Channing"],
    ["Learn to regard the souls around you as parts of some grand instrument. It is for each of us to know the keys and stops, that we may draw forth the harmonies that lie sleeping in the silent octaves.","Anonymous"],
    ["If evil be said of thee, and if it be true, correct thyself; if it be a lie, laugh at it.","Epictetus"],
    ["In many things it is not well to say, 'Know thyself'; it is better to say, 'Know others.' ","Menander"],
    ["The less people speak of their greatness, the more we think of it.","Lord Bacon"],
    ["He who sedulously attends, pointedly asks, calmly speaks, coolly answers and ceases when he has no more to say is in possession of some of the best requisites of man.","Johann Casper Lavater"],
    ["Men are more mindful of wrongs than of benefits.","Proverb"],
    ["A good word is an easy obligation; but not to speak ill requires only our silence; which costs us nothing.","John Tillotson"],
    ["It requires less character to discover the faults of others than is does to tolerate them.","J. Petit Senn"],
    ["Do not forget small kindnesses and do not remember small faults.","Chinese Proverb"],
    ["Go back a little to leap further.","John Clarke"],
    ["It is hard to fail, but it is worse never to have tried to succeed.","Theodore Roosevelt"],
    ["Half of the failures in life come from pulling one's horse when he is leaping.","Thomas Hood"],
    ["I failed my way to success.","Thomas Edison"],
    ["Our doubts are traitors, and make us lose the good we oft might win, by fearing to attempt.","William Shakespeare"],
    ["Every failure brings with it the seed of an equivalent success.","Napoleon Hill"],
    ["Failure is blindness to the strategic element in events; success is readiness for instant action when the opportune moment arrives.","Newell D. Hillis"],
    ["They fail, and they alone, who have not striven.","Thomas Bailey Aldrich"],
    ["We learn wisdom from failure much more than success. We often discover what we will do, by finding out what we will not do.","Samuel Smiles"],
    ["I was never afraid of failure, for I would sooner fail than not be among the best.","John Keats"],
    ["He that is down needs fear no fall.","John Bunyan"],
    ["Never let the fear of striking out get in your way.","George Herman 'Babe' Ruth"],
    ["One who fears failure limits his activities. Failure is only the opportunity to more intelligently begin again.","Henry Ford"],
    ["Only those who dare to fail greatly can ever achieve greatly.","John F. Kennedy"],
    ["The greatest mistake you can make in life is to continually be afraid you will make one.","Elbert Hubbard"],
    ["Failure is a trickster with a keen sense of irony and cunning. It takes great delight in tripping one when success is almost within reach.","Napoleon Hill"],
    ["Our greatest glory consist not in never falling, but in rising every time we fall.","Oliver Goldsmith"],
    ["What would life be if we had no courage to attempt anything?","Vincent van Gogh"],
    ["Bad times have a scientific value. These are occasions a good leaner would not miss.","Ralph Waldo Emerson"],
    ["The greatest men sometimes overshoot themselves, but then their very mistakes are so many lessons of instruction. ","Tom Browne"],
    ["A man of character finds a special attractiveness in difficulty, since it is only by coming to grips with difficulty that he can realize his potentialities.","Charles de Gaulle"],
    ["Experience teaches slowly, and at the cost of mistakes.","James A. Froude"],
    ["It is the want of diligence, rather than the want of means, that causes most failures.","Alfred Mercier"],
    ["A man's life is interesting primarily when he has failed--I well know. For it's a sign that he tried to surpass himself.","Georges Clemenceau"],
    ["He who fears being conquered is sure of defeat.","Napoleon Bonaparte"],
    ["There is no failure except in no longer trying.","Elbert Hubbard"],
    ["There is no impossibility to him who stands prepared to conquer every hazard. The fearful are the failing.","Sarah J. Hale"],
    ["Disappointments are to the soul what thunderstorms are to the air.","Johann C. F. von Schiller"],
    ["Failure teaches success.","Japanese Saying"],
    ["Don't waste your life in doubts and fears: spend yourself on the work before you, well assured that the right performance of this hour's duties will be the best preparation for the hours or ages that follow it.","Ralph Waldo Emerson"],
    ["No longer forward nor behind I look in hope and fear; But grateful take the good I find, The best of now and here.","John G. Whittier"],
    ["It is not work that kills men, it is worry. Work is healthy; you can hardly put more on a man than he can bear. But worry is rust upon the blade. It is not movement that destroys the machinery, but friction.","Henry Ward Beecher"],
    ["Never let life's hardships disturb you ... no one can avoid problems, not even saints or sages.","Nichiren Daishonen"],
    ["Ask yourself this question: 'Will this matter a year from now?'","Richard Carlson"],
    ["Surely there is something in the unruffled calm of nature that overawes our little anxieties and doubts; the sight of the deep-blue sky and the clustering stars above seems to impart a quiet to the mind.","Jonathan Edwards"],
    ["Do not anticipate trouble, or worry about what may never happen. Keep in the sunlight.","Benjamin Franklin"],
    ["Imagine every day to be the last of a life surrounded with hopes, cares, anger and fear. The hours that come unexpectedly will be much the more grateful.","Horace"],
    ["The mind that is anxious about future events is miserable.","Seneca"],
    ["Present fears are less than horrible imaginings.","William Shakespeare"],
    ["Let us be of good cheer, remembering that the misfortunes hardest to bear are those that never happen.","James Russel Lowell"],
    ["How much pain have cost us the evils that have never happened.","Thomas Jefferson"],
    ["It is the trouble that never comes that causes the loss of sleep.","Chas. Austin Bates"],
    ["Live in each season as it passes; breathe the air, drink the drink, taste the fruit, and resign yourself to the influences of each.","Henry David Thoreau"],
    ["We also deem those happy, who from the experience of life, have learned to bear its ills and without descanting on their weight.","Junvenal"],
    ["Thus each person by his fears gives wings to rumor, and, without any real source of apprehension, men fear what they themselves have imagined.","Lucan"],
    ["I never think of the future - it comes soon enough.","Albert Einstein"],
    ["It is idle to dread what you cannot avoid. Stultum est timere quod vitare non potes.","Publilius Syrus"],
    ["He either fears his fate too much, Or his deserts are small, Who dares not put it to the touch To gain or lose it all.","Marquis of Montrose"],
    ["The rose is fairest when it is budding new, and hope is brightest when it dawns from fears.","Walter Scott"],
    ["The block of granite which was an obstacle in the pathway of the weak, became a stepping-stone in the pathway of the strong.","Thomas Carlyle"],
    ["Press on! A better fate awaits thee.","Victor Hugo"],
    ["Perseverance is king.","Josh Billings"],
    ["The man who removes a mountain begins by carrying away small stones.","Chinese Proverb"],
    ["Nothing great is created suddenly, any more than a bunch of grapes or a fig.","Epictetus"],
    ["The important thing in life is to have great aim and to possess the aptitude and the perseverance to attain it.","Johann Wolfgang Von Goethe"],
    ["Success in life is a matter not so much of talent or opportunity as of concentration and perseverance.","C. W. Wendte"],
    ["I hold a doctrine, to which I owe not much, indeed, but all the little I ever had, namely, that with ordinary talent and extraordinary perseverance, all things are attainable.","Sir T. F. Buxton"],
    ["Those who would attain to any marked degree of excellence in a chosen pursuit must work, and work hard for it, prince or peasant.","Bayard Taylor"],
    ["Keep on going, and the chances are that you will stumble on something, perhaps when you are least expecting it. I never heard of anyone ever stumbling on something sitting down.","Charles F. Kettering"],
    ["Let me tell you the secret that has led me to my goal. My strength lies solely in my tenacity.","Louis Pasteur"],
    ["Persistent people begin their success where others end in failure.","Edward Eggleston"],
    ["There is nothing which persevering effort and unceasing and diligent care cannot overcome.","Seneca"],
    ["The drops of rain make a hole in the stone, not by violence, but by oft falling.","Lucretius"],
    ["He who would do some great thing in this short life, must apply himself to the work with such a concentration of his forces as to the idle spectators, who live only to amuse themselves, looks like insanity.","John Foster"],
    ["Great works are performed not by strength, but by perseverance.","Samuel Johnson"],
    ["The way of progress is neither swift nor easy.","Marie Curie"],
    ["Do not think that what is hard for thee to master is impossible for man; but if a thing is possible and proper to man, deem it attainable by thee.","Marcus Aurelius"],
    ["It does not matter how slowly you go so long as you do not stop.","Confucius"],
    ["No one can possibly achieve any real and lasting success or 'get rich' in business by being a conformist. ","J. Paul Getty"],
    ["No road is too long for him who advances slowly and does not hurry, and no attainment is beyond his reach who equips himself with patience to achieve it.","Jean de La Bruy&egrave;re"],
    ["Thomas Edison dreamed of a lamp that could be operated by electricity, began where he stood to put his dream into action, and despite more than ten thousand failures, he stood by that dream until he made it a physical reality. Practical dreamers do not quit.","Napoleon Hill"],
    ["Those who believe they are exclusively in the right are generally those who achieve something.","Aldous Huxley"],
    ["Dreams seldom materialize on their own.","Dian Fossey"],
    ["The hand that follows intellect can achieve.","Michelangelo"],
    ["Vigilance in watching opportunity; tact and daring in seizing upon opportunity; force and persistence in crowding opportunity to its utmost of possible achievement – these are the martial virtues which must command success.","Austin Phelps"],
    ["Whatsoever the mind has ordained for itself, it has achieved.","Seneca"],
    ["I attempt an arduous task; but there is no worth in that which is not a difficult achievement.","Ovid"],
    ["Effort only fully releases its reward after a person refuses to quit.","Napoleon Hill"],
    ["The secret of all great undertakings is hard work and self-reliance.","Gustavus F. Swift"],
    ["Shallow men believe in luck, strong men believe in cause and effect.","Ralph Waldo Emerson"],
    ["People sometimes attribute my success to my genius; all the genius I know anything about is hard work.","Alexander Hamilton"],
    ["Success is sweet, the sweeter if long delayed and attained through manifold struggles and defeats.","A. Bronson Alcott"],
    ["Much we learn only to forget it again; to stand by the goal, we must traverse all the way to it.","R&uuml;ckert"],
    ["Not the maker of plans and promises, but rather the one who offers faithful service in small matters. This is the person who is most likely to achieve what is good and lasting.","Johann Wolfgang von Goethe"],
    ["Great men are the modellers, patterns, and in a wide sense creators, of whatsoever the general mass of men contrived to do and attain.","Carlyle"],
    ["If the mass of people hesitate to act, strike thou in swift with all boldness; the noble heart that understands and seizes quick hold of opportunity can achieve everything.","Johann Wolfgang von Goethe"],
    ["Great opportunities come to all but many do not know they have met them. The only preparation to take advantage of them is simple fidelity to what each day brings.","A. E. Dunning"],
    ["The sure way to miss success is to miss the opportunity.","Victor Chasles"],
    ["Opportunity, sooner or later, comes to all who work and wish.","Lord Stanley"],
    ["Take all the swift advantage of the hours.","William Shakepeare"],
    ["Opportunities do not come with their values stamped upon them. Everyone must be challenged. A day dawns, quite like other days; in it a single hour comes, quite like other hours; but in that day and in that hour the chance of a lifetime faces us. ","Maltbie Davenport Babcock"],
    ["Welcome every new and difficult problem in life as a new opportunity to wrestle and win – and to gain new experience and new power.","L H. Murlin"],
    ["Many do with opportunities as children do at the seashore; they fill their little hands with sand, and then let the grains fall through, one by one.","Thomas Jones"],
    ["The future is an opportunity.","J. F. Ware"],
    ["To improve the golden moment of opportunity, and catch the good that is within our reach, is the great art of life.","Samuel Johnson"],
    ["A wise man will make more opportunities than he finds.","Francis Bacon"],
    ["Opportunities are on every hand; what we need is, not a new chance, but clearness of vision to discern the chance which at this very hour is ours, if we recognize it.","Katherine Krieger"],
    ["A man in earnest finds means or, if he cannot find, creates them.","William Ellery Channing"],
    ["Who seeks, and will not take, when once 'tis offered, Shall never find it more.","William Shakespeare"],
    ["And then one day you find ten years have got behind you. No one told you when to run, you missed the starting gun.","Time lyrics, Pink Floyd"],
    ["When the time comes in which one could, the time has passed in which one can.","Marie Ebner Eschenbach"],
    ["There's a time for all things.","William Shakespeare"],
    ["The golden moments in the stream of life rush past us, and we see nothing but sand; the angels come to visit us, and we only know them when they are gone.","George Eliot"],
    ["We have the power within, but the secret of success is to employ our power and talents and be prepared for opportunity when it comes.","Walter Matthews"],
    ["We must look for the opportunity in every difficulty instead of being paralyzed at the thought of the difficulty in every opportunity.","Walter E. Cole"],
    ["A good opportunity is seldom presented, and is easily lost.","Syrus"],
    ["The secret of success in life is for a man to be ready for his opportunity when it comes.","Benjamin Disraeli"],
    ["Who cannot but see oftentimes how strange the threads of our destiny run? Oft it is only for a moment the favorable instant is presented. We miss it, and months and years are lost.","Ludwig Tieck"],
    ["Present opportunities are not to be neglected; they rarely visit us twice.","Voltaire"],
    ["Arrange whatever pieces come your way.","Virginia Woolf"],
    ["The lure of the distant and the difficult is deceptive. The great opportunity is where you are.","John Burroughs"],
    ["Do not wait for ideal circumstances, nor for the best opportunities; they will never come.","Janet Erskine Stuart"],
    ["Occasions are rare: and those who know how to seize upon them are rarer.","H. W. Shaw"],
    ["Ability is of little account without opportunity.","Napoleon Bonaparte"],
    ["The greatest achievement of the human spirit is to live up to one's opportunities and make the most of one's resources.","Marquis de Vauvenargues"],
    ["Chance is always powerful; let your hook always be cast in a pool where you least expect there will be fish.","Ovid"],
    ["How often events, by chance and unexpectedly, come to pass, which you had not dared even to hope for!","Terence"],
    ["A stray, unthought-of five minutes may contain the event of a life, and this all-important moment – who can tell when it will be upon us?","Dean Alford"],
    ["Do not suppose opportunity will knock twice at your door.","Nicolas de Chamfort"],
    ["Improve time in the present; for opportunity is precious, and time is a sword.","Saadi"],
    ["Cherish your visions and your dreams as they are the children of your soul, the blueprints of your ultimate achievements.","Napoleon Hill"],
    ["The key to success is to focus our conscious mind on things we desire not things we fear.","Brian Tracy"],
    ["Success is getting what you want. Happiness is wanting what you get.","Dale Carnegie"],
    ["Obstacles are necessary for success because in selling, as in all careers of importance, victory comes only after many struggles and countless defeats.","Og Mandino"],
    ["A real decision is measured by the fact that you've taken a new action. If there's no action, you haven't truly decided.","Tony Robbins"],
    ["If you can't control your anger, you are as helpless as a city without walls waiting to be attacked.","The Book of Proverbs"],
    ["A mediocre person tells. A good person explains. A superior person demonstrates. A great person inspires others to see for themselves.","Harvey Mackay"],
    ["Freedom, privileges, options, must constantly be exercised, even at the risk of inconvenience.","Jack Vance"],
    ["Take care of your body. It's the only place you have to live.","Jim Rohn"],
    ["You can have everything in life you want, if you will just help other people get what they want.","Zig Ziglar"],
    ["The number of times I succeed is in direct proportion to the number of times I can fail and keep on trying.","Tom Hopkins"],
    ["You have everything you need to build something far bigger than yourself.","Seth Godin"],
    ["Fall seven times, stand up eight.","Japanese proverb"],
    ["Never put off till tomorrow what you can do today.","Thomas Jefferson"],
    ["Those who do not learn from history are doomed to repeat it.","George Santayana"],
    ["The future belongs to those who believe in the beauty of their dreams.","Eleanor Roosevelt"],
    ["People who are unable to motivate themselves must be content with mediocrity, no matter how impressive their other talents.","Andrew Carnegie"],
    ["The definition of insanity is doing the same thing over and over and expecting different results.","Benjamin Franklin"],
    ["Find out what you like doing best and get someone to pay you for doing it.","Katherine Whitehorn"],
    ["One important key to success is self-confidence. An important key to self-confidence is preparation.","Arthur Ashe"],
    ["Success consists of going from failure to failure without loss of enthusiasm.","Winston Churchill"],
    ["Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy.","Norman Vincent Peale"],
    ["Big jobs usually go to the men who prove their ability to outgrow small ones.","Ralph Waldo Emerson"],
    ["Do one thing every day that scares you.","Eleanor Roosevelt"],
    ["I'm playing; I'm here. I'm going to fight until they tell me they don't want me anymore.","Steve Nash"],
    ["Don't be afraid to fail. Don't waste energy trying to cover up failure. Learn from your failures and go on to the next challenge. It's OK to fail. If you're not failing, you're not growing.","H. Stanley Judd"],
    ["Take risks: if you win, you will be happy; if you lose, you will be wise.","Unknown"],
    ["Opportunities don't often come along. So, when they do, you have to grab them.","Audrey Hepburn"],
    ["Never say anything about yourself you do not want to come true.","Brian Tracy"],
    ["When one door closes, another opens; but we often look so long and so regretfully upon the closed door that we do not see the one which has opened for us.","Alexander Graham Bell"],
    ["Choose a job you love, and you will never have to work a day in your life.","Confucius"],
    ["Success doesn't come to you, you go to it.","Marva Collins"],
    ["Only those who dare to fail greatly can ever achieve greatly.","Robert F. Kennedy"],
    ["Never tell me the sky's the limit when there are footprints on the moon.","Unknown"],
    ["It is never too late to be what you might have been.","George Eliot"],
    ["All our dreams can come true, if we have the courage to pursue them.","Walt Disney"],
    ["Every experience in your life is being orchestrated to teach you something you need to know to move forward.","Brian Tracy"],
    ["I'm a great believer in luck, and I find the harder I work, the more I have of it.","Thomas Jefferson"],
    ["Nothing in the world can take the place of persistence. Talent will not; nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. Education will not; the world is full of educated derelicts. Persistence and determination alone are omnipotent. The slogan &ldquo;press on&rdquo; has solved and will always solve the problems of the human race.","Calvin Coolidge"],
    ["If you don't like something, change it. If you can't change it, change your attitude.","Maya Angelou"],
    ["Whenever you are asked if you can do a job, tell &lsquo;em, &lsquo;Certainly I can!' Then get busy and find out how to do it.","Theodore Roosevelt"],
    ["The more wisdom you attain and the more conscious you will become, the crazier you will appear to others.","Unknown"],
    ["People will forget what you said, people will forget what you did, but people will never forget how you made them feel.","Maya Angelou"],
    ["Vision without action is merely a dream. Action without vision just passes time. Vision with action can change the world.","Joel Barker"],
    ["We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.","Plato"],
    ["The reasonable man adapts himself to the world: the unreasonable one persists in trying to adapt the world to himself. Therefore all progress depends on the unreasonable man.","George Bernard Shaw"],
    ["A genuine leader is not a searcher for consensus but a molder of consensus.","Martin Luther King, Jr."],
    ["A good leader takes a little more than his share of the blame, a little less than his share of the credit.","Arnold H. Glasow"],
    ["A leader is best when people barely know he exists, when his work is done, his aim fulfilled, they will say: we did it ourselves.","Lao Tzu"],
    ["A leader is one who knows the way, goes the way, and shows the way.","John C. Maxwell"],
    ["Be a yardstick of quality. Some people aren't used to an environment where excellence is expected.","Steve Jobs"],
    ["Don't find fault, find a remedy.","Henry Ford"],
    ["Effective leadership is putting first things first. Effective management is discipline, carrying it out.","Stephen Covey"],
    ["Enlightened leadership is spiritual if we understand spirituality not as some kind of religious dogma or ideology but as the domain of awareness where we experience values like truth, goodness, beauty, love and compassion, and also intuition, creativity, insight and focused attention.","Deepak Chopra"],
    ["Good management is the art of making problems so interesting and their solutions so constructive that everyone wants to get to work and deal with them.","Paul Hawken"],
    ["High expectations are the key to everything.","Sam Walton"],
    ["Hold yourself responsible for a higher standard than anybody expects of you. Never excuse yourself.","Henry Ward Beecher"],
    ["I suppose leadership at one time meant muscles; but today it means getting along with people.","Mahatma Gandhi"],
    ["If you think you can do a thing or think you can't do a thing, you're right.","Henry Ford"],
    ["If your actions inspire others to dream more, learn more, do more and become more, you are a leader.","John Quincy Adams"],
    ["Innovation distinguishes between a leader and a follower.","Steve Jobs"],
    ["It is better to lead from behind and to put others in front, especially when you celebrate victory when nice things occur. You take the front line when there is danger. Then people will appreciate your leadership.","Nelson Mandela"],
    ["Lead, follow, or get out of the way.","Thomas Paine"],
    ["Leadership - leadership is about taking responsibility, not making excuses.","Mitt Romney"],
    ["Leadership and learning are indispensable to each other.","John F. Kennedy"],
    ["Leadership is solving problems. The day soldiers stop bringing you their problems is the day you have stopped leading them. They have either lost confidence that you can help or concluded you do not care. Either case is a failure of leadership.","Colin Powell"],
    ["Leadership is the capacity to translate vision into reality.","Warren Bennis"],
    ["Leadership to me means duty, honor, country. It means character, and it means listening from time to time.","George W. Bush"],
    ["Management is doing things right; leadership is doing the right things.","Peter Drucker"],
    ["Only the guy who isn't rowing has time to rock the boat.","Jean-Paul Sartre"],
    ["Outstanding leaders go out of their way to boost the self-esteem of their personnel. If people believe in themselves, it's amazing what they can accomplish.","Sam Walton"],
    ["People ask the difference between a leader and a boss. The leader leads, and the boss drives.","Theodore Roosevelt"],
    ["Speak softly and carry a big stick; you will go far.","Theodore Roosevelt"],
    ["The quality of a leader is reflected in the standards they set for themselves.","Ray Kroc"],
    ["The task of the leader is to get his people from where they are to where they have not been.","Henry A. Kissinger"],
    ["When you can't make them see the light, make them feel the heat.","Ronald Reagan"],
    ["When your values are clear to you, making decisions becomes easier.","Roy E. Disney"],
    ["Where there is no vision, there is no hope.","George Washington Carver"],
    ["I am not a product of my circumstances. I am a product of my decisions.","Stephen Covey"],
    ["Never discourage anyone who continually makes progress, no matter how slow.","Plato"],
    ["If you want to be happy, set a goal that commands your thoughts, liberates your energy, and inspires your hopes","Andrew Carnegie"],
    ["I avoid looking forward or backward, and try to keep looking upward","Charlotte Bronte"],
    ["Change will not come if we wait for some other person or some other time. We are the ones we've been waiting for. We are the change that we seek.","Barack Obama"],
    ["Change almost never fails because it's too early. It almost always fails because it's too late","Seth Godin"],
    ["What we achieve inwardly will change outer reality.","Plutarch"],
    ["Hardship often prepares an ordinary person for an extraordinary destiny.","Christopher Markus"],
    ["Management is doing things right; leadership is doing the right things.","Peter Drucker"],
    ["Personal leadership is the process of keeping your vision and values before you and aligning your life to be congruent with them.","Stephen Covey"],
    ["Nearly all men can stand adversity, but if you want to test a man's character, give him power.","Abraham Lincoln"],
    ["There will be plenty of other problems in the future. This is as good a time as any to get ahead of them.","Stan Slap"],
    ["Unleash the potential that is in another and you unleash the potential that is in you.","Matshona Dhliwayo"],
    ["Achieving your goal is great. Exceeding your goal is exceptional. Exceeding your goal and teaching others is Leadership","Joseph Swenson"],
    ["You gain strength, courage and confidence by every experience in which you really stop to look fear in the face. You must do the thing you think you cannot do.","Eleanor Roosevelt"],
    ["Leaders don’t create followers, they create more leaders.","Tom Peters"],
    ["The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things.","Ronald Reagan"],
    ["Don't tell people how to do things, tell them what to do and let them surprise you with their results.","George Patton"],
    ["In the end, it is important to remember that we cannot become what we need to be by remaining what we are.","Max De Pree"],
    ["Every company has a culture. The only question is whether or not you decide what it is.","Jason Cohen"],
    ["You have to be run by ideas, not hierarchy. The best ideas have to win, otherwise good people don't stay!","Steve Jobs"],
    ["A person's success in life can usually be measured by the number of uncomfortable conversations he or she is willing to have.","Tim Ferriss"],
    ["As much as talent counts, effort counts twice.","Angela Duckworth"],
    ["The chains of habit are too weak to be felt until they are too strong to be broken.","Samuel Johnson"],
    ["The more elaborate our means of communication, the less we communicate.","Joseph Priestley"],
    ["An old trick well done is far better than a new trick with no effect.","Harry Houdini"],
    ["If you wish to see the truth then hold no opinions.","Chien-chih Seng-ts'an"],
    ["The world is full of people who know the price of everything, but the value of nothing.","Phillip Fisher"],
    ["There never was a good knife made of bad steel.","Benjamin Franklin"],
    ["When an archer is shooting for nothing, he has all his skill. If he shoots for a brass buckle, he is already nervous. If he shoots for a prize of gold, he goes blind or sees two targets. He is out of his mind. His skill has not changed. But the prize divides him. He cares. He thinks more of winning than of shooting And the need to win drains him of power.","Chuang Tzu"],
    ["The pessimist complains about the wind; the optimist expects it to change; the realist adjusts the sails.","William Arthur Ward"],
    ["Managers manage the known, leaders manage the unknown.","Tim Armstrong"],
];
