<?php
$quotes = [
	["Give me six hours to chop down a tree and I will spend the first four sharpening the axe.","Abraham Lincoln"],
	["We are what we repeatedly do. Excellence, then, is not an act, but a habit.","Aristotle"],
	["You see things; and you say Why? But I dream things that never were; and I say Why not?","George Bernard Shaw"],
	["Opportunity is missed by most people because it is dressed in overalls and looks like work.","Thomas Edison"],
	["If you're going through hell, keep going.","Winston Churchill"],
	["If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much.","Jim Rohn"],
	["Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.","Thomas Edison"],
	["Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice.","Wayne Dyer"],
	["I don't believe you have to be better than everybody else. I believe you have to be better than you ever thought you could be.","Ken Venturi"],
	["Even if you fall on your face, you're still moving forward.","Victor Kiam"],
	["We are taught you must blame your father, your sisters, your brothers, the school, the teachers - but never blame yourself. It's never your fault. But it's always your fault, because if you wanted to change you're the one who has got to change.","Katharine Hepburn"],
	["Things do not happen. Things are made to happen.","John F. Kennedy"],
	["You have to learn the rules of the game. And then you have to play better than anyone else.","Albert Einstein"],
	["I'd rather attempt to do something great and fail than to attempt to do nothing and succeed.","Robert H. Schuller"],
	["You can't build a reputation on what you are going to do.","Henry Ford"],
	["The secret of getting ahead is getting started.","Mark Twain"],
	["Small deeds done are better than great deeds planned.","Peter Marshall"],
	["The wise do at once what the fool does at last.","Baltasar Gracian"],
	["Without inspiration the best powers of the mind remain dormant. There is a fuel in us which needs to be ignited with sparks.","Johann Gottfried Von Herder"],
	["If the wind will not serve, take to the oars.","Latin Proverb"],
	["You cannot plough a field by turning it over in your mind.","Unknown"],
	["Do not wait to strike till the iron is hot; but make it hot by striking.","William B. Sprague"],
	["If the highest aim of a captain were to preserve his ship, he would keep it in port forever.","Thomas Aquinas"],
	["An oak is not felled at one blow.","Spanish Proverb"],
	["Discipline is doing what you hate to do. And doing it like you love it.","Mike Tyson"],
	["Knowing is not enough; we must apply. Willing is not enough; we must do.","Johann Wolfgang von Goethe"],
	["Nothing great was ever achieved without enthusiasm.","Ralph Waldo Emerson"],
	["Constant dripping hollows out a stone.","Lucretius"],
	["Try not to become a man of success but a man of value.","Albert Einstein"],
	["Don't wait for extraordinary opportunities. Seize common occasions and make them great.","Orison Swett Marden"],
	["You miss 100% of the shots you don't take.","Wayne Gretzky"],
	["Nothing can stop the man with the right mental attitude from achieving his goal; nothing on earth can help the man with the wrong mental attitude. ","Thomas Jefferson"],
	["Success does not consist in never making blunders, but in never making the same one a second time.","Josh Billings"],
	["Careful thinking and hard work will solve nearly all your problems. Try and see for yourself.","Ullery"],
	["The talent of success is nothing more than doing what you can do, well.","Henry Longfellow"],
	["Success is the sum of small efforts, repeated day in and day out.","Robert Collier"],
	["In the hopes of reaching the moon men fail to see the flowers that blossom at their feet.","Albert Schweitzer"],
	["The fool doth think he is wise, but the wise man knows himself to be a fool.","William Shakespeare"],
	["The best way to make your dreams come true is to wake up.","Paul Valery"],
	["You cannot dream yourself into a character; you must hammer and forge yourself one.","Henry David Thoreau"],
	["Do not follow where the path may lead. Go instead where there is no path and leave a trail.","Harold McAlindon"],
	["Leadership: The art of getting someone else to do something you want done because he wants to do it.","Dwight D. Eisenhower"],
	["What chance gathers she easily scatters. A great person attracts great people and knows how to hold them together.","Johann Wolfgang Von Goethe"],
	["The real leader has no need to lead - he is content to point the way.","Henry Miller"],
	["Not the cry, but the flight of a wild duck, leads the flock to fly and follow.","Chinese Proverb"],
	["If your actions inspire others to dream more, learn more, do more and become more, you are a leader.","John Quincy Adams"],
	["He who has never learned to obey cannot be a good commander.","Aristotle"],
	["The ultimate measure of a man is not where he stands in moments of comfort, but where he stands at times of challenge and controversy.","Martin Luther King"],
	["Any one can hold the helm when the sea is calm.","Publilius Syrus"],
	["Never tell people how to do things. Tell them what to do and they will surprise you with their ingenuity.","George Patton"],
	["Misfortunes, untoward events, disclose the skill of a general, while success conceals his weakness.","Horace"],
	["The greater a man is in power above others, the more he ought to excel them in virtue. None ought to govern who is not better than the governed.","Publilius Syrus"],
	["Take time to deliberate; but when the time for action arrives, stop thinking and go in.","Andrew Jackson"],
	["To be a great leader and so always master of the situation, one must of necessity have been a great thinker. An eagle was never yet hatched from a goose's egg.","James Thomas"],
	["He who has learned how to obey will know how to command.","Solon"],
	["When I give a minister an order, I leave it to him to find the means to carry it out.","Napoleon Bonaparte"],
	["A ruler should be slow to punish and swift to reward.","Ovid"],
	["No man is good enough to govern another man without that other's consent.","Abraham Lincoln"],
	["No general can fight his battles alone. He must depend upon his lieutenants, and his success depends upon his ability to select the right man for the right place.","Philip Armour"],
	["To do great things is difficult; but to command great things is more difficult.","Friedrich Nietzsche"],
	["It is absurd that a man should rule others, who cannot rule himself.","Latin Proverb"],
	["Let him who would be moved to convince others, be first moved to convince himself.","Thomas Carlyle"],
	["A good general not only sees the way to victory; he also knows when victory is impossible.","Polybius"],
	["A goal is a dream with a deadline.","Napoleon Hill"],
	["If you don't know where you are going, you'll end up someplace else.","Yogi Berra"],
	["To reach a port, we must sail. Sail, not drop anchor. Sail, not drift.","Franklin Roosevelt"],
	["Our plans miscarry because they have no aim. When a man does not know what harbor he is making for, no wind is the right wind.","Seneca"],
	["It is not enough to take steps which may some day lead to a goal; each step must be itself a goal and a step likewise.","Johann Wolfgang von Goethe"],
	["A good archer is known not by his arrows but by his aim.","Thomas Fuller"],
	["Who aims at excellence will be above mediocrity; who aims at mediocrity will be far short of it.","Burmese Saying"],
	["If each of us hires people who are smaller than we are, we shall become a company of dwarfs. But if each of us hires people who are bigger than we are, we shall become a company of giants.","David Ogilvy"],
	["It is easier to be wise for others than for ourselves.","Francois De La Rochefoucauld"],
	["A wise man learns by the mistakes of others, a fool by his own.","Latin Proverb"],
	["No man was ever wise by chance.","Seneca"],
	["The fact is, that to do anything in the world worth doing, we must not stand back shivering and thinking of the cold and danger, but jump in and scramble through as well as we can.","Robert Cushing"],
	["The only journey is the journey within.","Rainer Maria Rilke"],
	["It is not easy to find happiness in ourselves, and it is not possible to find it elsewhere.","Agnes Repplier"],
	["Our business in life is not to get ahead of other people, but to get ahead of ourselves.","Maltbie Matlock"],
	["The most difficult thing in life is to know yourself.","Thales"],
	["He that will not reflect is a ruined man.","Asian Proverb"],
	["Every day do something that will inch you closer to a better tomorrow.","Doug Firebaugh"],
	["Be not afraid of growing slowly; be afraid only of standing still.","Chinese Proverb"],
	["Knowing yourself is the beginning of all wisdom.","Aristotle"],
	["Our ideas, like orange-plants, spread out in proportion to the size of the box which imprisons the roots.","Edward Bulwer Lytton"],
	["It is only the very wisest and the very stupidest who cannot change.","Confucius"],
	["We are either progressing or retrograding all the while; there is no such thing as remaining stationary in this life.","James Freeman Clarke"],
	["Everybody wants to be somebody; nobody wants to grow.","Johann Wolfgang von Goethe"],
	["A man who finds no satisfaction in himself will seek for it in vain elsewhere.","La Rochefoucauld"],
	["Fear less, hope more, eat less, chew more, whine less, breathe more, talk less, say more, hate less, love more, and good things will be yours.","Swedish Proverb"],
	["Make it thy business to know thyself, which is the most difficult lesson in the world.","Miguel de Cervantes"],
	["The secret of many a man's success in the world resides in his insight into the moods of men and his tact in dealing with them.","J. G. Holland"],
	["Arguing with a fool proves there are two.","Doris M. Smith"],
	["Look to be treated by others as you have treated others.","Publilius Syrus"],
	["Success in life, in anything, depends upon the number of person's that one can make himself agreeable to.","Thomas Carlyle"],
	["Let us believe neither half of the good people tell us of ourselves, nor half of the evil they say of others.","J. Petit Senn"],
	["The more you say, the less people remember.","Francois Fenelon"],
	["Never lose a chance of saying a kind word.","William Thackeray"],
	["The soul of conversation is sympathy.","Thomas Campbell"],
	["It is always good to know, if only in passing, charming human beings. It refreshes one like flowers and woods and clear brooks.","George Eliot"],
	["Every man is a volume if you know how to read him.","William Ellery Channing"],
	["If evil be said of thee, and if it be true, correct thyself; if it be a lie, laugh at it.","Epictetus"],
	["The less people speak of their greatness, the more we think of it.","Lord Bacon"],
	["He who sedulously attends, pointedly asks, calmly speaks, coolly answers and ceases when he has no more to say is in possession of some of the best requisites of man.","Johann Casper Lavater"],
	["A good word is an easy obligation; but not to speak ill requires only our silence; which costs us nothing.","John Tillotson"],
	["Do not forget small kindnesses and do not remember small faults.","Chinese Proverb"],
	["It is hard to fail, but it is worse never to have tried to succeed.","Theodore Roosevelt"],
	["Half of the failures in life come from pulling one's horse when he is leaping.","Thomas Hood"],
	["Our doubts are traitors, and make us lose the good we oft might win, by fearing to attempt.","William Shakespeare"],
	["They fail, and they alone, who have not striven.","Thomas Bailey Aldrich"],
	["We learn wisdom from failure much more than success. We often discover what we will do, by finding out what we will not do.","Samuel Smiles"],
	["He that is down needs fear no fall.","John Bunyan"],
	["The greatest mistake you can make in life is to continually be afraid you will make one.","Elbert Hubbard"],
	["Our greatest glory consist not in never falling, but in rising every time we fall.","Oliver Goldsmith"],
	["What would life be if we had no courage to attempt anything?","Vincent van Gogh"],
	["A man's life is interesting primarily when he has failed--I well know. For it's a sign that he tried to surpass himself.","Georges Clemenceau"],
	["There is no failure except in no longer trying.","Elbert Hubbard"],
	["Don't waste your life in doubts and fears: spend yourself on the work before you, well assured that the right performance of this hour's duties will be the best preparation for the hours or ages that follow it.","Ralph Waldo Emerson"],
	["Never let life's hardships disturb you; no one can avoid problems, not even saints or sages.","Nichiren Daishonen"],
	["Ask yourself this question: 'Will this matter a year from now?'","Richard Carlson"],
	["Present fears are less than horrible imaginings.","William Shakespeare"],
	["How much pain have cost us the evils that have never happened.","Thomas Jefferson"],
	["It is the trouble that never comes that causes the loss of sleep.","Austin Bates"],
	["The block of granite which was an obstacle in the pathway of the weak, became a stepping-stone in the pathway of the strong.","Thomas Carlyle"],
	["The man who removes a mountain begins by carrying away small stones.","Chinese Proverb"],
	["Nothing great is created suddenly, any more than a bunch of grapes or a fig.","Epictetus"],
	["Keep on going, and the chances are that you will stumble on something, perhaps when you are least expecting it. I never heard of anyone ever stumbling on something sitting down.","Charles Kettering"],
	["Persistent people begin their success where others end in failure.","Edward Eggleston"],
	["The drops of rain make a hole in the stone, not by violence, but by oft falling.","Lucretius"],
	["Great works are performed not by strength, but by perseverance.","Samuel Johnson"],
	["The way of progress is neither swift nor easy.","Marie Curie"],
	["It does not matter how slowly you go so long as you do not stop.","Confucius"],
	["Dreams seldom materialize on their own.","Dian Fossey"],
	["I attempt an arduous task; but there is no worth in that which is not a difficult achievement.","Ovid"],
	["Shallow men believe in luck, strong men believe in cause and effect.","Ralph Waldo Emerson"],
	["We must look for the opportunity in every difficulty instead of being paralyzed at the thought of the difficulty in every opportunity.","Walter Cole"],
	["The lure of the distant and the difficult is deceptive. The great opportunity is where you are.","John Burroughs"],
	["Do not wait for ideal circumstances, nor for the best opportunities; they will never come.","Janet Erskine Stuart"],
	["Success is getting what you want. Happiness is wanting what you get.","Dale Carnegie"],
	["Obstacles are necessary for success because in selling, as in all careers of importance, victory comes only after many struggles and countless defeats.","Og Mandino"],
	["A real decision is measured by the fact that you've taken a new action. If there's no action, you haven't truly decided.","Tony Robbins"],
	["A mediocre person tells. A good person explains. A superior person demonstrates. A great person inspires others to see for themselves.","Harvey Mackay"],
	["The number of times I succeed is in direct proportion to the number of times I can fail and keep on trying.","Tom Hopkins"],
	["Fall seven times, stand up eight.","Japanese proverb"],
	["People who are unable to motivate themselves must be content with mediocrity, no matter how impressive their other talents.","Andrew Carnegie"],
	["The definition of insanity is doing the same thing over and over and expecting different results.","Benjamin Franklin"],
	["Success consists of going from failure to failure without loss of enthusiasm.","Winston Churchill"],
	["Don't be afraid to fail. Don't waste energy trying to cover up failure. Learn from your failures and go on to the next challenge. It's OK to fail. If you're not failing, you're not growing.","H. Stanley Judd"],
	["Take risks: if you win, you will be happy; if you lose, you will be wise.","Unknown"],
	["When one door closes, another opens; but we often look so long and so regretfully upon the closed door that we do not see the one which has opened for us.","Alexander Graham Bell"],
	["Success doesn't come to you, you go to it.","Marva Collins"],
	["Only those who dare to fail greatly can ever achieve greatly.","Robert F. Kennedy"],
	["Nothing in the world can take the place of persistence. Talent will not; nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. Education will not; the world is full of educated derelicts. Persistence and determination alone are omnipotent. The slogan 'press on' has solved and will always solve the problems of the human race.","Calvin Coolidge"],
	["If you don't like something, change it. If you can't change it, change your attitude.","Maya Angelou"],
	["People will forget what you said, people will forget what you did, but people will never forget how you made them feel.","Maya Angelou"],
	["Vision without action is merely a dream. Action without vision just passes time. Vision with action can change the world.","Joel Barker"],
	["We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.","Plato"],
	["A genuine leader is not a searcher for consensus but a molder of consensus.","Martin Luther King"],
	["A good leader takes a little more than his share of the blame, a little less than his share of the credit.","Arnold Glasow"],
	["A leader is best when people barely know he exists, when his work is done, his aim fulfilled, they will say: we did it ourselves.","Lao Tzu"],
	["A leader is one who knows the way, goes the way, and shows the way.","John C. Maxwell"],
	["Be a yardstick of quality. Some people aren't used to an environment where excellence is expected.","Steve Jobs"],
	["Don't find fault, find a remedy.","Henry Ford"],
	["Effective leadership is putting first things first. Effective management is discipline, carrying it out.","Stephen Covey"],
	["Good management is the art of making problems so interesting and their solutions so constructive that everyone wants to get to work and deal with them.","Paul Hawken"],
	["Hold yourself responsible for a higher standard than anybody expects of you. Never excuse yourself.","Henry Ward Beecher"],
	["I suppose leadership at one time meant muscles; but today it means getting along with people.","Mahatma Gandhi"],
	["If you think you can do a thing or think you can't do a thing, you're right.","Henry Ford"],
	["If your actions inspire others to dream more, learn more, do more and become more, you are a leader.","John Quincy Adams"],
	["It is better to lead from behind and to put others in front, especially when you celebrate victory when nice things occur. You take the front line when there is danger. Then people will appreciate your leadership.","Nelson Mandela"],
	["Lead, follow, or get out of the way.","Thomas Paine"],
	["Leadership is solving problems. The day soldiers stop bringing you their problems is the day you have stopped leading them. They have either lost confidence that you can help or concluded you do not care. Either case is a failure of leadership.","Colin Powell"],
	["Leadership is the capacity to translate vision into reality.","Warren Bennis"],
	["Only the guy who isn't rowing has time to rock the boat.","Jean-Paul Sartre"],
	["Outstanding leaders go out of their way to boost the self-esteem of their personnel. If people believe in themselves, it's amazing what they can accomplish.","Sam Walton"],
	["People ask the difference between a leader and a boss. The leader leads, and the boss drives.","Theodore Roosevelt"],
	["Speak softly and carry a big stick; you will go far.","Theodore Roosevelt"],
	["The quality of a leader is reflected in the standards they set for themselves.","Ray Kroc"],
	["The task of the leader is to get his people from where they are to where they have not been.","Henry Kissinger"],
	["When your values are clear to you, making decisions becomes easier.","Roy Disney"],
	["Never discourage anyone who continually makes progress, no matter how slow.","Plato"],
	["Change almost never fails because it's too early. It almost always fails because it's too late","Seth Godin"],
	["Management is doing things right; leadership is doing the right things.","Peter Drucker"],
	["Personal leadership is the process of keeping your vision and values before you and aligning your life to be congruent with them.","Stephen Covey"],
	["Nearly all men can stand adversity, but if you want to test a man's character, give him power.","Abraham Lincoln"],
	["Unleash the potential that is in another and you unleash the potential that is in you.","Matshona Dhliwayo"],
	["Achieving your goal is great. Exceeding your goal is exceptional. Exceeding your goal and teaching others is Leadership","Joseph Swenson"],
	["You gain strength, courage and confidence by every experience in which you really stop to look fear in the face. You must do the thing you think you cannot do.","Eleanor Roosevelt"],
	["Leaders don’t create followers, they create more leaders.","Tom Peters"],
	["The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things.","Ronald Reagan"],
	["Don't tell people how to do things, tell them what to do and let them surprise you with their results.","George Patton"],
	["In the end, it is important to remember that we cannot become what we need to be by remaining what we are.","Max De Pree"],
	["Every company has a culture. The only question is whether or not you decide what it is.","Jason Cohen"],
	["You have to be run by ideas, not hierarchy. The best ideas have to win, otherwise good people don't stay!","Steve Jobs"],
	["A person's success in life can usually be measured by the number of uncomfortable conversations he or she is willing to have.","Tim Ferriss"],
	["As much as talent counts, effort counts twice.","Angela Duckworth"],
	["The chains of habit are too weak to be felt until they are too strong to be broken.","Samuel Johnson"],
	["The more elaborate our means of communication, the less we communicate.","Joseph Priestley"],
	["An old trick well done is far better than a new trick with no effect.","Harry Houdini"],
	["If you wish to see the truth then hold no opinions.","Chien-chih Seng-ts'an"],
	["The world is full of people who know the price of everything, but the value of nothing.","Phillip Fisher"],
	["There never was a good knife made of bad steel.","Benjamin Franklin"],
	["When an archer is shooting for nothing, he has all his skill. If he shoots for a brass buckle, he is already nervous. If he shoots for a prize of gold, he goes blind or sees two targets. He is out of his mind. His skill has not changed. But the prize divides him. He cares. He thinks more of winning than of shooting And the need to win drains him of power.","Chuang Tzu"],
	["The pessimist complains about the wind; the optimist expects it to change; the realist adjusts the sails.","William Arthur Ward"],
	["Managers manage the known, leaders manage the unknown.","Tim Armstrong"],
];
